### ISSUE TITLE
Wallet Bugs Pre-Solana Migration

### ISSUE THREAD

**Issue by Perronef5** [helium/wallet-app#133]
- Token Selector showing wrong token for payment screen and token swap. 
- Update token list to use `useTokenAccount`.
- tokenList bottom sheet not going full length when banner is showing.
- Wallets with over 20 hotspots not showing up on initial state
- NFTs not showing up in nfts tab

**Comment by Perronef5** [comment]
> hey! sent myself a couple devnet NFTs to my new Helium Solana address. unable to view the NFTs in the Helium wallet, unable to see the SPL tokens in solscan. reply with any questions if you want more troubleshooting or additional info. thanks for your hard work
> 
> new address: [2LRcUWzmMrjuAvgmhXFcGih4EUeTKZ5aFe2xcwxt2zgB](https://solscan.io/account/2LRcUWzmMrjuAvgmhXFcGih4EUeTKZ5aFe2xcwxt2zgB?cluster=devnet) ![image](https://user-images.githubusercontent.com/94848716/225961600-6a442d3a-22df-45dd-9c94-77931461509a.png)
> 
> ![image](https://user-images.githubusercontent.com/94848716/225961697-4ce595ae-5b79-4687-9884-e38aabf86073.png)
> 
> https://solscan.io/account/4jrDfmQT9TVy4jSbpb5Ki3qsU2xLR6btJieaaMBgnrpy?cluster=devnet
> 
> ![image](https://user-images.githubusercontent.com/94848716/225962575-f88d19a0-5fec-483d-911c-dd4f829f4931.png)
> 
> Update: I went against recommendations and entered my new SOL Helium wallet private key into solflare [i feel like i've got a solid understanding of how keypairs are stored and transactions are signed and don't feel at risk, but please educate me if that was just an insanely dumb thing to do] and the NFTs and devnet shitcoins do appear in my new Helium SPL address. So i did receive them, just unable to view them in the app (SPL tokens i was told not to expect to see, still unable to see the NFTs tho) thanks!

Hi @ilovespectra thanks for helping us test! I'll look into fixing that NFT issue. As for other devnet tokens we currently do not support that but there is an open PR adding just that 🙂

**Comment by ilovespectra** [comment]
Hey! wondering if I should delete and reinstall the app to get this update? I'm still unable to view my NFTs in the Helium Wallet. Here's the NFTs in my solflare wallet:
![image](https://user-images.githubusercontent.com/94848716/226375078-a5d69b1e-29de-4af6-b1ac-ba48c6732e3b.png)

Here's the Solana wallet address again:
2LRcUWzmMrjuAvgmhXFcGih4EUeTKZ5aFe2xcwxt2zgB

Here's a link to one of the devnet NFTs
https://solscan.io/token/Fiwsrjy32J3LwtebkZhPMSZajCxr6LzSKPDSkPwM5DVm?cluster=devnet#holders

Here's the account that was created for the NFT:
https://solscan.io/account/FLjA3MZNaLidtyXz7wNLYnitjPf21sAhoh1vdG3cGv3w?cluster=devnet

Here's a fresh screenshot of my Helium Wallet NFTs:
![image](https://user-images.githubusercontent.com/94848716/226376617-fde5ebe1-60f4-4d94-8bf2-54fd138db089.png)

ps- I see a second 0 balance `Helium Mobile` account in my wallet when i view it in solflare. maybe sketch?
Here is an associated account:
7kgMAoDCujxmLFrxq5ek7SHTKeDE6i19DDHXJHur5Pm4
![image](https://user-images.githubusercontent.com/94848716/226374807-33618d97-9756-4918-9bbe-15bb993310b5.png)



thanks again for your help
