### ISSUE TITLE
Added RAK miners to the "Solana experience" wallet by mistake

### ISSUE THREAD

**Issue by bullyard** [helium/wallet-app#138]
I accidentally added 2 IOT miners to SOL devnet! I know transactions can not be reversed, just wondering what the best course of action would be. thanks for your help!

IOT hotspots on SOL devnet: "FORMAL CLOTH DOVE" and "SPECIAL SAGE CAT"

addresses of the miners: 
11cuuwgghMdhaRbhjSLR1f32g5zZyqZmnrc8r3ssHmcvw8a9nWT 
112TptZGehwTx3gWXkt9bKdRrEdGuedCo1Ky9qc8BW93XE1cAw1z

This is the testnet/solana wallet address:
48x19ybJKHe8K1bbXcsVaKhkuk1MSiwRDCTPn7HgS9aR

This is the real helium wallet address:
13JGnMwFCSgM11dEt78chTsUsZaa5CbJy8KFWz2E4f2EDMaRbsj

**Comment by ChewingGlass** [comment]
I think you should be fine to leave them on solana devnet. None of this state is getting migrated to solana mainnet.

**Comment by bullyard** [comment]
Thanks Chew, the problem is that i cant onboard them on mainnet. :/ Take a look at some of the responses i get when trying to register them: 

https://api.helium.io/v1/pending_transactions/Tz9P5r8dl6Q6IMG8Q9VEiYehopKFsPpMvXbyfRDl3T0
https://api.helium.io/v1/pending_transactions/rQENdMvFqHncXT1XNkk0cAZd4fvovhUDWOpmd3ooZPU
https://api.helium.io/v1/pending_transactions/gRywIx2HH-kiK84NXpqsnv5WfYna-a4a2khodQa4rQI
