### ISSUE TITLE
Cannot send IOT or MOBILE from Black Wallet App

### ISSUE THREAD

**Issue by deasydoesit** [helium/wallet-app#180]
**Describe the bug**
In the Black Wallet App, users are unable to send IOT or MOBILE. It doesn't matter how much SOL the account has, or if the receiving account has IOT or MOBILE already. 

**To Reproduce**

1. Transfer IOT or MOBILE

**Expected behavior**
IOT and MOBILE should be able to be sent from Black Wallet app

**Smartphone (please complete the following information):**

- Device: iPhone, but maybe Android as well
- OS: iOS, but maybe Android as well
- App Version: 2.0.4

**Comment by butter14** [comment]
Top issue as far as I'm concerned. 

Whenever I send a IOT/MOBILE token to another SOLANA wallet like Phantom from the Helium Black Wallet, it fails to complete, at first confirming I'm sending on "Solana-mainnet-beta Payment" which I click "I understand." I then swipe to send to the wallet. Then I get a "Transaction Failed: failed to send transaction:Transaction simulation failed:Error processing Instruction 0:Custom Program error 0x12"

**Comment by Perronef5** [comment]
This has been addressed on 2.0.6

**Comment by deasydoesit** [comment]
Seeing this as being addressed in 2.0.6 as well. Going to close the issue.
