### ISSUE TITLE
Decimal Points Incorrect When Receiving MOBILE 

### ISSUE THREAD

**Issue by deasydoesit** [helium/wallet-app#181]
**Describe the bug**
When a MOBILE transaction is received on the Black Wallet App, the decimal point is off by 2.

**To Reproduce**

1. Receive a MOBILE txn

**Expected behavior**
MOBILE should accept proper decimal placement

**Screenshots**
MOBILE txn sent from Phantom:
<img src="https://user-images.githubusercontent.com/37127765/233201262-7aee5901-c2a0-4c0f-aabb-d4e319f33e1e.png"  width="300"> 

MOBILE txn received on Black Wallet App:
<img src="https://user-images.githubusercontent.com/37127765/233201495-6dcb3566-a900-47f0-b613-acb0a93e17cb.png"  width="300">

**Smartphone (please complete the following information):**

- Device: iPhone, but maybe Android as well
- OS: iOS, but maybe Android as well
- App Version: 2.0.4

**Additional context**

**Comment by Perronef5** [comment]
Should be fixed on 2.0.6

**Comment by deasydoesit** [comment]
Seeing this as fixed in 2.0.6, will close issue
