### ISSUE TITLE
Default URL in In-App Browser says “?devnet” even when on Mainnet

### ISSUE THREAD

**Issue by deasydoesit** [helium/wallet-app#182]
**Describe the bug**
See title

**Screenshots**

![httpsapp realms todaycluster=devnet](https://user-images.githubusercontent.com/37127765/233202814-827a516f-22cc-4beb-a0c3-db672ebaf691.png)

**Comment by Perronef5** [comment]
Fixed in version 2.0.6

**Comment by deasydoesit** [comment]
Seeing this as being fixed in 2.0.6, closing issue.
