### ISSUE TITLE
Hotspots activity not showing in app

### ISSUE THREAD

**Issue by shnoah641** [helium/wallet-app#193]
**Describe the bug**
Hotspots activity not showing in app

**To Reproduce**

1. Go to 'helium hnt wallet'
2. Click on '$ then hnt balance'
3. See error 

**Expected behavior**
I expect it to show my balance but it does not 

**Screenshots**
![20230420_112432](https://user-images.githubusercontent.com/72530034/233455325-22b2d607-57c8-4541-bdcc-b88dc6b1310d.jpg)

**Smartphone (please complete the following information):**

- Device: Motorola One 5G Ace
- OS: Android 11
- App Version 2.0.4

**Additional context**

**Comment by tintent** [comment]
I am have issues  I have zero  activity in rewards for the past 4 days since they started this move

**Comment by iulianaac** [comment]
Same to me. Since the migration zero activities for my 4 devices.

**Comment by deasydoesit** [comment]
If you do not see your claimable rewards, these fixes have solved the issue for most people: 

1. Upgrade your app on Android and iOS to at least version 2.0.5
2. Ensure you’re not on Devnet. Go into Settings > toggle off “Solana Devnet preview” > toggle back on > toggle back off

https://discord.com/channels/404106811252408320/730418759298318346/1098808301015273522

**Comment by tintent** [comment]
Yes now I see that we receive IOT tokens instead of helium. Okay so how do
cashout my IOS ? move it out of the helium app? Am in the west USA I have
been using crpto.com, but now with IOT I can't. So what wallet can I use,
becuese  my coinbase acct. Cant help ether.i trying phantom but seems the
transaction fails to send everytime.

**Comment by tintent** [comment]
Nevermind I found it.
