### ISSUE TITLE
Claimable IOT/MOBILE Decimals Incorrect

### ISSUE THREAD

**Issue by deasydoesit** [helium/wallet-app#194]
**Describe the bug**
When you select a hotspot and view its claimable rewards, the amount shown doesn't include decimal points. For example, if a hotspot had earned 1.099 IOT, the app shows the claimable amount as 1099 IOT.

**To Reproduce**

1. Click hotspot
2. View claimable rewards

**Expected behavior**
It should show the correct value

**Screenshots**

In the screenshot below, the actual rewards are 5899.831203 IOT, not 5899831203 IOT

![image-7_2](https://user-images.githubusercontent.com/37127765/233482846-a9e71f4f-7f74-477b-aa5e-073b0d612753.png)

**Comment by shawaj** [comment]
Can confirm this on Android 13 on s23 ultra

**Comment by Perronef5** [comment]
This is fixed and should be in the next release
