### ISSUE TITLE
Ledger Helium migration issues

### ISSUE THREAD

**Issue by HoBoWAN** [helium/wallet-app#195]
When I try to migrate my Ledger Helium wallet and I use the migration tool the address that the tool detects is not the one that Ledger live displays for my Solana Wallet, why is that. How can I be sure I am migrating to the right wallet and that I will be able access my HNT in the new wallet?

**Comment by Juweii** [comment]
It seems this is similar to my issue: https://github.com/helium/wallet-app/issues/205
Is it?

**Comment by deasydoesit** [comment]
**Ledger integration with Helium Wallet App not supported**

If you are using a Ledger Wallet to hold your tokens, you need to migrate the Ledger Wallet when you want to access the Helium tokens on your Ledger. You can find the Ledger migration guide here: 

https://www.youtube.com/watch?v=Sl7UBStRmpA 

You cannot integrate your Ledger App with your Helium Wallet App. If you want to explore the Solana ecosystem with a Ledger Wallet, Solflare is a great option and can connect directly to your Ledger: 

https://support.ledger.com/hc/en-us/articles/7723954701469-How-to-access-your-Solana-tokens?support=true
