### ISSUE TITLE
iOS App crashes when tapping "Enter SOL Amount"

### ISSUE THREAD

**Issue by bigbuffer** [helium/wallet-app#200]
When trying to send SOL through the black helium app it will crash upon tapping the amount to send.

Tested on multiple different iPhones iOS 16.4.1 Helium app Version 2.0.5

Steps:
1. Open app
2. Tap SOL tokens
3. Tap send
4 App will crash when tapping "Enter SOL Amount"
![IMG_0856](https://user-images.githubusercontent.com/57190198/233697818-82a0256b-130e-491b-b0f5-a196f23ed6da.PNG)

**Comment by Perronef5** [comment]
Fixed in 2.0.6

**Comment by deasydoesit** [comment]
2.0.6 is pending review in the Apple App Store and will be released shortly.

**Comment by Talitrus** [comment]
Can confirm this works in 2.0.6 for me now.
