### ISSUE TITLE
Android App v2.06 doesn't open

### ISSUE THREAD

**Issue by rel100** [helium/wallet-app#203]
The Android app freezes on the logo, I try 3 different devices (all samsung) Android 13 and Android 9 all three devices do the same thing, was good on v2.05.

**Comment by rel100** [comment]
https://cdn.discordapp.com/attachments/1071217040888692917/1099358857358221323/Screenshot_20230422_093819_Logcat_Extreme.jpg

**Comment by rel100** [comment]
Here The LOGs from my android device with Android 13
[Log_2023-04-22_10-11-55.txt](https://github.com/helium/wallet-app/files/11301744/Log_2023-04-22_10-11-55.txt)

**Comment by AndreTimUA** [comment]
Moto G31 Android 12 doesn't open App Wallet 2.0.6

**Comment by lesterm5150** [comment]
Can confirm. Tried on android 9 and 13 to no avail. It freezes at logo screen.

**Comment by AndreTimUA** [comment]
All fixed! Great!!!
