### ISSUE TITLE
Sending Sol error

### ISSUE THREAD

**Issue by Songopav** [helium/wallet-app#204]
![IMG-20230422-WA0000](https://user-images.githubusercontent.com/131515949/233768866-d6e82139-2943-46c0-809c-73487d730f56.jpg)
**Describe the sending sol to sol address error

**To Reproduce**

1. Send sol
2. Amount 
3. Send 

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- App Version [e.g. 3.3.0]

**Additional context**

**Comment by deasydoesit** [comment]
What version of the Helium Wallet App are you on? If you haven't done so already, please try updating to the latest version on Android (e.g., 2.0.6) to see if that addresses the issue.

**Comment by Songopav** [comment]
Latest now works
