### ISSUE TITLE
Helium Wallet Ledger migration just finished, but no access to the Solana wallet

### ISSUE THREAD

**Issue by Juweii** [helium/wallet-app#205]
**Describe the bug**
Hey all, on my Helium Wallet I have a local and a Ledger Account (default). When opened the Helium Walled today, the HNT/IOT/SOL were just empty (HNT/IOT/SOL = 0).
Then I switched to the on-phone wallet - it started migration and showed up that amount of HNT for this wallet.
Then I switched back to the Ledger account and it also started migration. After that it shows up the correct amount of HNT and also IOT on the wallet.
However, it seems there has been a new Solana wallet created and linked in the background which doesn't belongs to the Ledger device, because the public key at "Share" does not belong to any of my Solana wallets on the Ledger... However, I can't reveal any private key here, because its a Ledger linked wallet.

How to access that Solana Wallet??

Solflare also not showing up any active wallets when using the Ledger device...

Then I found theres a migration tool, but on account 0 I get this error:
<img width="845" alt="image" src="https://user-images.githubusercontent.com/5314938/233770888-9f6d8210-95d4-4ac9-a99c-1e8ace6c14a4.png">

So it seems this is because the migration is already done by the Helium Wallet App.

But how to access the Solana wallet with my HNT??

**To Reproduce**

1. Open the Helium Wallet
2. It shows 0 balance
3. Switch to another wallet (local wallet)
4. It starts and finishes migration
5. Balance shown
6. Switch to the ledger wallet
7. It starts and finishes migration
8. Balance shown
9. Solflare not showing up this Solana account when using the ledger

**Expected behavior**
Having the HNT/IOT/SOL visible to Solana account when using the Ledger account on Solflare.

**Screenshots**

**Smartphone (please complete the following information):**

- iPhone 14 Pro

**Additional context**
If my worst feeling comes true and the app automatically migrates the account and creates a NEW Solana account, how can I reveal the words for that generated private key?

**Comment by Juweii** [comment]
Is there any way to undo the Migration from the Helium Wallet (Black) app, so that the [Migration Tool](https://docs.helium.com/solana/migration/ledger/) would work again??

**Comment by Juweii** [comment]
When looking at the Account on Solana explorer using the account address shown in the App and also shown in the migration step 2, it shows the account balance and not "Account does not exist" like shown in the video:
https://youtu.be/Sl7UBStRmpA?t=331

So does that mean the migration is not complete and my balance is not lost?

**Comment by deasydoesit** [comment]
**Ledger integration with Helium Wallet App not supported**

If you are using a Ledger Wallet to hold your tokens, you need to migrate the Ledger Wallet when you want to access the Helium tokens on your Ledger. You can find the Ledger migration guide here:

https://www.youtube.com/watch?v=Sl7UBStRmpA

You cannot integrate your Ledger App with your Helium Wallet App. If you want to explore the Solana ecosystem with a Ledger Wallet, Solflare is a great option and can connect directly to your Ledger:

https://support.ledger.com/hc/en-us/articles/7723954701469-How-to-access-your-Solana-tokens?support=true

Also, when using the migration tool, make sure you have Ledger Live closed

**Comment by Juweii** [comment]
Unfortunately the migration tool doesn't work, as mentioned above:
![image](https://user-images.githubusercontent.com/5314938/233799084-d356cd27-5b23-432c-8d00-078cf92ad013.png)
If I choose account 1, the process works properly. However, in that account are not any of my coins, just tested if that would work.

**Comment by Juweii** [comment]
Ok, what I have found with the help of the moderator jas_williams is, that the migration is not finished.
The "migration", the app shows, doesn't change the derivation path (at least not for ledger wallets). It seems its just for received the initial SOL/IOT to activate the Solana account (something like that) when looking on solscan.
My wallet is still on the Helium derivation path and the issue is, that this Sign Transactions just doesn't work.
Not sure if this is still related to the app or if this is a different story, maybe this issue can be closed here.

**However, I would recommend to show more details about what is happening when the App says "Migrating your wallet to Solana" => "You've successfully migrated your tokens!" also for ledger Devices.**

**Comment by Juweii** [comment]
Created the issue with new details at https://github.com/helium/helium-program-library/issues/204
So this issue here will be closed.
