### ISSUE TITLE
Feature Request: Enhanced User Security From Scam NFTs

### ISSUE THREAD

**Issue by HansaFL** [helium/wallet-app#206]
**Describe the bug**
Mobile App should warn users about scam NFTs that can randomly appear in the wallet. Interacting with the NFT can empty the funds in the wallet, and users unfamiliar with the Solana Ecosystem may be an easy vector for hackers.  

Users randomly receive NFTs in their Wallet that are scams and vectors of attack. Users not familiar with the Solana ecosystem are particularly at risk. 

**Screenshots**
[Example of a scam NFT in the Helium Wallet](https://imgur.com/a/vkGN7xS)

**All User's are Particulary at Risk:**

**Comment by Ryan-Goldstein** [comment]
Thanks for sharing this - I created an issue addressing the same concern: https://github.com/helium/wallet-app/issues/202

**Comment by jthiller** [comment]
Closing as duplicate of #202
