### ISSUE TITLE
rent-based transaction error when sending SOL

### ISSUE THREAD

**Issue by Talitrus** [helium/wallet-app#211]
An Android user reported being allowed to send SOL but receiving this error and failure when trying to do so. User reports having more than sufficient SOL.
Helium Wallet version 2.0.6

![IMG_20230423_200501898_HDR](https://user-images.githubusercontent.com/9120001/233857630-9a4c1d5a-5807-4338-b9fb-17072325d36d.jpg)

_Originally posted by @Talitrus in https://github.com/helium/wallet-app/issues/210#issuecomment-1519125250_

**Comment by Talitrus** [comment]
May be related to #204 , but this user reports being 2.0.6

**Comment by Perronef5** [comment]
If solana is coming back with this error then the user does not have enough sol

**Comment by Perronef5** [comment]
We now show an error indicating the user does not have enough SOL. Additionally, this ticket https://github.com/helium/wallet-app/issues/277 will make it much less likely

**Comment by jthiller** [comment]
closed as solved by https://github.com/helium/wallet-app/issues/277
