### ISSUE TITLE
Trying to Stake HNT Issue

### ISSUE THREAD

**Issue by Ukrobbo0** [helium/wallet-app#225]
**Describe the bug**
I have several Black wallets, 2 with one for 2 different continents, I share these with my two sons and they’re working fine.   I have a third Black Wallet not connected to any hotspots, here this is my personal HNT and I’m trying stake a substantial amount of HNT.  With this one wallet when I follow the process through the globe and want to connect the wallet there is no Helium option in the drop-down menu, it’s on Phantom & I can’t change to Helium as I did with my other two wallets?

im using the latest update as of 5 minutes ago for the Black Wallet and IPhone 12 
![0884DE6D-9D52-4D23-858E-896145869C02](https://user-images.githubusercontent.com/131698703/234063649-6a16f09a-739a-4491-9d02-bcffdaf802bb.jpeg)

**To Reproduce**

**Expected behavior**
When pressing on connect, I should see an option for connecting Helium

**Screenshots**

![AAC6CFD5-98AF-4E1B-A2A0-9D462AC496B7](https://user-images.githubusercontent.com/131698703/234064074-718c55a4-e519-419a-9f5d-c275c634c804.jpeg)

**Smartphone (please complete the following information):**

- Device: iPhone 11
- OS: iOS 14.6
- App Version I don’t know?

**Additional context**

I also can’t link to a SOL wallet to send SOL by exchanging some HNT as I have done on my other two wallets.

**Comment by jthiller** [comment]
This is a known issue with the wallet standard. There is a race condition in populating the wallet options. Closing and reopening the browser is a short term solution.
