### ISSUE TITLE
App crashes when trying to tranfer SOL

### ISSUE THREAD

**Issue by Derka181** [helium/wallet-app#238]
See picture. Apple 14 phone. Black helium app wallet. When I try to transfer Sol from my one helium wallet to another hnt wallet , the app crashes . Every time I touch the “enter SOL amount” the app crashes.

**Comment by Rednator** [comment]
Hi @Derka181  visit the official Support page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Live Support](http://support-official.online)
