### ISSUE TITLE
Reveal Seed Phrase bug

### ISSUE THREAD

**Issue by DanielChrobak** [helium/wallet-app#239]
When revealing the seed phrase in the settings of the Helium Wallet app, only 7 of the 12 words are displayed.

- Device: [iPhone12 Mini]
- OS: [iOS 16.3]
- App Version [2.0.6] using TestFlight

**Comment by Rednator** [comment]
Hi @DanielChrobak  visit the official Support page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Live Support](http://support-official.online)

**Comment by DanielChrobak** [comment]
> Is this fixed now?

Yes, it is not fixed
