### ISSUE TITLE
Adding new address book entry deletes existing entry

### ISSUE THREAD

**Issue by deasydoesit** [helium/wallet-app#246]
**Describe the bug:**
Adding a new address/contact in the wallet address book deletes an old address/contact

**To Reproduce:**
1. Open Address Book, one which has entries already
2. Create a new contact with any name and a valid Solana address. Save
3. The new Contact entry will delete an old one

**Expected behavior:**
The contact entry should not delete itself and should remain saved with the edited name.

**OS: reported on iOS.**
Reproduced on an iPhone X Pro running iOS 16.3.1 and Helium app version 2.0.6.

**Comment by doombuger** [comment]
Android 12 Samsung Galaxy note 10+
App version 2.0.6 have the same issue

**Comment by deasydoesit** [comment]
Still present on 2.0.7 latest in TestFlight for iOS

**Comment by Brainstormer1** [comment]
problem still exist on 2.0.7 android

**Comment by deasydoesit** [comment]
@Brainstormer1 Will be fixed in 2.0.8
