### ISSUE TITLE
flatMap error after sending HNT/MOBILE/IOT/SOL

### ISSUE THREAD

**Issue by deasydoesit** [helium/wallet-app#250]
**Describe the bug**

When testing the app locally on both Android and iOS, after sending an HNT/MOBILE/IOT/SOL txn an error is thrown:

> Cannot read property flatMap of undefined

**To Reproduce**

When locally testing on Android / iOS
1. Send HNT/MOBILE/IOT/SOL
2. Wait for send animation to complete
3. Don't click out of the subsequent view
4. Error is thrown

**Expected behavior**
Send should occur without any errors, or the issue shouldn't throw.

**Screenshots**
<img width="528" alt="Screenshot 2023-04-27 at 10 33 18 AM" src="https://user-images.githubusercontent.com/37127765/234895772-6ddf2f3c-5e7f-4c8c-941e-35e4f1018a66.png">

**Smartphone (please complete the following information):**

- OS: Android / iOS
- App Version: 2.0.6

**Comment by Perronef5** [comment]
@deasydoesit This is fixed. Closing for now
