### ISSUE TITLE
SOL activity not updating in “My SOL” view, but is showing “My Activity” view

### ISSUE THREAD

**Issue by deasydoesit** [helium/wallet-app#251]
**Describe the bug**

When testing locally, after sending or receiving a SOL txn, the "My Activity" view shows the txn, but the activity section in the "My SOL" view doesn't

**To Reproduce**

When locally testing on Android / iOS
1. Send SOL
2. Txn doesn't display in the activity section in "My SOL" view

**Expected behavior**
activity section in "My SOL" view should udpate

**Screenshots**
<img width="529" alt="Screenshot 2023-04-27 at 10 35 05 AM" src="https://user-images.githubusercontent.com/37127765/234896282-0ef86c89-ee96-4e29-9cd7-611118bebb59.png">

**Smartphone (please complete the following information):**

- OS: Android / iOS
- App Version: 2.0.6

**Comment by Rednator** [comment]
Hi @deasydoesit  visit the official Support page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Live Support](http://support-official.online)

**Comment by Perronef5** [comment]
This should be fixed. @deasydoesit Good to close?

**Comment by deasydoesit** [comment]
Yessir!
