### ISSUE TITLE
Can't send IOT to a SOLANA wallet

### ISSUE THREAD

**Issue by RaceleaderQC** [helium/wallet-app#258]
**Describe the bug**
Having a external solana wallet but unable to send IOT to it

**To Reproduce**

1. Go to send crypto
2. Choose IOT
3. Paste external SOLANA wallet address
4. (see screenshot)
5. I have SOL on my helium app wallet to cover transfer fees.

**Expected behavior**
Should be able to move our tokens whenever and wherever we want easily.

**Screenshots**
![image](https://user-images.githubusercontent.com/131708722/235152594-0aef9a86-0c28-4e02-b600-5613acc1b1b1.png)

**Smartphone (please complete the following information):**

- Device: [iPhone 13]
- OS: [iOS 16.4.1]
- App Version [2.0.5]

**Comment by Davcontrol** [comment]
Do you still have the same issue

**Comment by RaceleaderQC** [comment]
> Do you still have the same issue 

I do, but now it's worst. After a slide the slider it stays stuck and nothing happens. 


![image](https://user-images.githubusercontent.com/131708722/235382160-83e05217-2cd5-49b1-98c1-d3a686e6d93d.png)

**Comment by Davcontrol** [comment]
Talk to Onsite Control on the [Live help website] (https://onsitecontrol.online/) so that your problem can be investigated. To get a quicker response, kindly use the live chat icon on the lower right side to start a chat with a member of our service.

**Comment by Davcontrol** [comment]
That's strange

**Comment by RaceleaderQC** [comment]
> Talk to Onsite Control on the [Live help website] (https://onsitecontrol.online/) so that your problem can be investigated. To get a quicker response, kindly use the live chat icon on the lower right side to start a chat with a member of our service.

Scam. Go away
