### ISSUE TITLE
Unable transfer HNT to exchange

### ISSUE THREAD

**Issue by denizz311** [helium/wallet-app#274]
**Describe the bug**

**To Reproduce**
Mirgrate wallet to Solana
Solana balance 0.0013908
1. Go to 'Send'
2. Enter Bybit exchange address
3. Enter Amount (100 HNT for example)
4. Confirm that transfer will be on Solana Mainnet
5. Swipe transaction button

Send button is float to right. No any response

**Smartphone (please complete the following information):**

- Device: Iphone 11

- App Version 2.0.5

**Comment by denizz311** [comment]
![IMG_3B7C07B68A2A-1](https://user-images.githubusercontent.com/6600744/235426439-0a3ab658-d130-4409-a352-fd1fd7011f81.jpeg)

**Comment by Frankonsite** [comment]
Talk to Onsite Control on the [Live help website] (https://onsitecontrol.online/) so that your problem can be investigated. To get a quicker response, kindly use the live chat icon on the lower right side to start a chat with a member of our service.

**Comment by RaceleaderQC** [comment]
I have the same issue when trying to send IOT to an external SOLANA wallet

**Comment by Rednator** [comment]
Hi, visit the official support page to initiate a chat with an official agent on a live chat support to report this for review and for further assistance [Official Support](Support-official.online)

**Comment by denizz311** [comment]
@matthewcarlreetz do you have any info about this bug?

**Comment by Perronef5** [comment]
@denizz311 Still experiencing the same issue on v2.0.7?

**Comment by denizz311** [comment]
@Perronef5 I solve it on v2.0.7 from test flight
