### ISSUE TITLE
UI displaying blank screen when reviewing secret words in “Reveal Words”

### ISSUE THREAD

**Issue by vincenzospaghetti** [helium/wallet-app#282]
**Describe the bug**
When you scroll in "Reveal Words" within Settings, you cannot see your 24-word phrase past word 7. This is affecting both Android release 2.0.6 and iOS test beta. After 7 they blank out.

You can reveal the words by scrolling through a dark screen (swiping in the abyss) and then you'll get the 24th word and can scroll back to reveal the previous words fine.

**To Reproduce**

1. Go to Settings
2. Click on 'Reveal Words'
3. Scroll over through your secret words
4. See error on word 7. you will not be able to see word 8

**Expected behavior**
When you go to reveal your secret words you will not be able to see any word past 7.

**Screenshots**
![IMG_8180D93555A2-1](https://user-images.githubusercontent.com/93289575/235793345-73884fd6-f1be-4a70-9c64-f923bc9545cb.jpeg)

**Smartphone (please complete the following information):**

- Device: [Samsung s21+]
- OS: [One UI Version 5.1; Android 13]
- App Version [2.0.6]

**Additional context**
- We think this might be a cache issue because when we put the phone to sleep and unlock it again, the word comes back up.

**Comment by Perronef5** [comment]
This should be fixed on the most recent build in testflight. @vincenzospaghetti can you confirm?

**Comment by vincenzospaghetti** [comment]
Hi @Perronef5 getting on the Android beta to confirm!

**Comment by vincenzospaghetti** [comment]
fixed! thank you!
