### ISSUE TITLE
Activity section refreshing non-stop

### ISSUE THREAD

**Issue by keenanhelium84** [helium/wallet-app#287]
**Describe the bug**
When in the wallet and clicking on either HNT, MOBILE or IOT. the activity space below will endlessly refresh and flicker, the cpu will also ramp up causing excess heat and fast battery drain. 

**To Reproduce**

This error occurred when sending funds between two different wallets on the app. I had sent a small portion of HNT, MOBILE and IOT to my other wallet. After sending tokens, the area below, the "activity" area, will constantly flicker and refresh infinitely. this causes the cpu to spike and the phone to get very warm. Closing the app, sleeping the phone have had no effect. 

If the app is reopened and I click on either HNT, IOT or MOBILE. the glitch happens. However, this does not happen for SOL or DC. 

**Expected behavior**
The activity section should check for an update once, then stop. 

**Screenshots**

https://user-images.githubusercontent.com/132491201/236023362-3c41c9a4-c109-4a8f-9beb-649697aa48af.MP4

**Smartphone (please complete the following information):**

- Device: iPhone 13 Pro Max
- OS: 16.3.1
- App Version 2.0.7 (16831311581

**Additional context**
specifically testing app

**Comment by Perronef5** [comment]
This should be fixed. @keenanhelium84 Good to close?
