### ISSUE TITLE
How to un mint my hotspot

### ISSUE THREAD

**Issue by HARJA2** [helium/wallet-app#289]
How do you un mint a hotspot: some how l compressed my nft in the helium wallet, and sent it to my solona wallet in crypto. Com, of it never got to crypto. Com and now my hotspot doesn't appear in the helium wallet. Does anyone know how to reverse this action or resolved?

**Comment by Perronef5** [comment]
This action is irreversible. I suggest you contact crypto.com and see if they can help you

**Comment by HARJA2** [comment]
Ok
