### ISSUE TITLE
Money (SOL) disappeared in the transfer process

### ISSUE THREAD

**Issue by Berkmf** [helium/wallet-app#291]
I wanted to transfer some SOL in my wallet to another account.
Both wallet addresses are correct!
The operation appears to have been successful. But about $150 was gone. It disappeared !

https://explorer.solana.com/tx/2Ndj1LVugUXEiRTKteQW2SeA7oJ9a7CDWz2nXEytVnNVZCfqfiG2Tey7DTHL77LTYZA8zBHdEyPucFyvw45uxTrm?cluster=mainnet-beta

**How will I trust this system?**
There is already very little profit being made. The money earned in this way also disappears

**SENDING ACCOUNT**
[sRbSU7mdE8f33bFKwXrrUbLzH3dJyUyiPtj4iGgJrwC](https://explorer.solana.com/address/sRbSU7mdE8f33bFKwXrrUbLzH3dJyUyiPtj4iGgJrwC?cluster=mainnet-beta)

**SENT ACCOUNT**
[DpoPNxDXqpvUp6rWQAVD4oi7KgUtz3dWU94827YunpUv](https://explorer.solana.com/address/DpoPNxDXqpvUp6rWQAVD4oi7KgUtz3dWU94827YunpUv?cluster=mainnet-beta)

I HAVE ACCESS TO BOTH ACCOUNTS, NO MONEY (SOL) IN BOTH

**Comment by Perronef5** [comment]
This transaction shows only 0.1 SOL was transferred. Closing as the transaction shows successful, only 0.1 SOL was transferred and sol transfers were fixed in v2.0.7
