### ISSUE TITLE
Issue viewing/interacting with seed words on 5 inch iphone

### ISSUE THREAD

**Issue by keenanhelium84** [helium/wallet-app#293]
**Describe the bug**
Unable to scroll through seed words on iphone se (5 inch model)

**To Reproduce**

When creating a new wallet, when reaching the "keep these words safe" screen, scrolling of the words is not functioning and are partially cut off screen. the only button that works on the screen, is the X to exit. 

**Expected behavior**
Should be able to scroll and savew seed words.

**Screenshots**
![IMG_2205](https://user-images.githubusercontent.com/132491201/236297631-dd0b2e96-9731-4f0d-9a3e-2d0f8a2eb034.jpg)

**Smartphone (please complete the following information):**

- Device: iphone se 
- OS: 15.7.5
- App Version 2.0.7 (1683157812)

**Additional context**
none

**Comment by ChewingGlass** [comment]
This may be fixed by [#365](https://github.com/helium/wallet-app/issues/365)
