### ISSUE TITLE
Fail To Claim

### ISSUE THREAD

**Issue by MinerJ76** [helium/wallet-app#302]
**Describe the bug**
I Have upgraded to 2.0.7. but the wallet still fails to claim my current IOT with failed txs.

**To Reproduce**

1. Go to Claim rewards
2. Click on Add to account
4. See error Failed to run txs

**Expected behavior**
Expected to add current rewards to account

**Screenshots**
The app doesn't allow for screenshots; it just gives a black screen

**Smartphone (please complete the following information):**

- Device: Motorola 5g Stylus
- OS: Android 12
- App Version 2.0.7.

**Additional context**
This problem has been consistent since app version 2.0.5.

**Comment by Talitrus** [comment]
What's your SOL token balance in the wallet? You may not have enough SOL. Are you comfortable sharing a wallet address?

**Comment by ChewingGlass** [comment]
Failure is due to not enough sol
