### ISSUE TITLE
DC burn transactions must have a recipient address

### ISSUE THREAD

**Issue by PieterPoncelet** [helium/wallet-app#355]
**Describe the bug**
As a Hotspot Maker you need to provide enough DC on your Maker Wallet for customers to onboard + location assert their Hotspots. As a Hotspot Maker you purchase HNT in another wallet (due to the fact that you cannot use the Maker Wallet), and swap these for DC whilst adding a Recipient for these DC's. 
While performing the swap from HNT to DC, it is absolutely necessary for the user to double check if the "Add Recepient +" field is properly filled with the Maker Solana Wallet. If not, the DC's will be burnt on the "intermediate" wallet and are lost, or so it seems.
What is the purpose of being able to burn DC's into any Wallet anyways? Shouldn't this be disabled by default?

**To Reproduce**

1. Click on 'swap',
2. Click on 'Understood',
3. Select 'HNT' and 'DC'
4. Insert a faulty "Add recipient +" address to transfer the DC's to,
5. DC's are burnt onto the current wallet, instead of onto the Maker Wallet. 

**Expected behavior**
A clear and concise message should be displayed that the DC's will be burnt onto the current wallet and will not be transferable to any other wallet hereafter!

**Screenshots**

**Smartphone (please complete the following information):**

- Device: any
- OS: any
- App Version : 2.0.7 and 2.0.8

**Additional context**

**Comment by Talitrus** [comment]
For instructions on how to burn DC to a wallet address, see here. https://docs.helium.com/hotspot-makers/become-a-maker/funding-a-maker-account/

This doesn't seem like a bug, but perhaps it could be a feature request for the transaction simulation screen to show a receiving address and ask for confirmation. Is that something that would have been helpful?

**Comment by ChewingGlass** [comment]
This seems like it might be bug if it's in invalid recipient address, should validation error to keep you from sending.

**Comment by cokes518** [comment]
Agree with @ChewingGlass. a valid address must be in the recipient field in order to complete the transaction burn DC. updating the title of the bug to make it more clear.

**Comment by ChewingGlass** [comment]
I think we should also change the language around Add Recipient to make it clear that it's optional.

**Comment by ChewingGlass** [comment]
A lot of users just want to buy DCs to their own wallet so they can do things like Assert Location. The UX there would mean having to type in your own wallet. Seems odd?
