### ISSUE TITLE
Cannot use jup.ag for swapping: the helium wallet cannot be connected

### ISSUE THREAD

**Issue by paperphoton** [helium/wallet-app#357]
**Describe the bug**

When using the helium wallet app (aka the black app), use of jup.ag for crypto swap is not possible: the helium wallet cannot be connected to the jup.ag platform (no any specific error or notification appear). Besides, there is no helium wallet on the list of possible wallets to use.

Moreover, it is not possible to connect other wallets like Phantom: although the Phantom app is installed, the jup.ag via helium app cannot see it. 

**To Reproduce**

1. Go to 'black helium app, "globe" tab'
2. Click on 'https://jup.ag'

**Expected behavior**
Normally, according to the videos on youtube provided by the helium comunity, after the transition to jup.ag there should be a notification about connection of the helium wallet to jup.ag. After pressing the button "Connect", another notification will pop up saying that the helium wallet is connected. 

**Smartphone (please complete the following information):**

- Device: [Redmi Note 8 Pro]
- OS: MIUI Global 11.05 Stable [Android 9 PPR1.180610.011]
- OS UPD:  updated to MIUI Global 12.0.8 Stable [Android 10 QP1A.190711.020] 
- App Version [2.0.8]

**Additional context**
The problem has been there since the solana migration. Regular wallet updates did not solve it.

**Comment by Talitrus** [comment]
Does the problem still happen after force-closing and re-opening the app or restarting your phone?

**Comment by paperphoton** [comment]
> Does the problem still happen after force-closing and re-opening the app or restarting your phone?

Yes, neither force stop nor restarting helps. Moreover, I also updated the OS to MIUI Global 12.0.8 Stable [Android 10 QP1A.190711.020] and it did not change anything.

**Comment by ChewingGlass** [comment]
If Phantom is also not working, this is likely an issue with Jupiter and not Helium. I would suggest asking in their discord or help channels.

**Comment by paperphoton** [comment]
> If Phantom is also not working, this is likely an issue with Jupiter and not Helium. I would suggest asking in their discord or help channels.

The problem can be in the embedded browser of the Helium wallet app. When I use a separate browser app like Brave, jup.ag successfully finds and connects to the Phantom wallet. 

The question is who is responsible for the embedded browser functioning and whom should I contact?

**Comment by 1t3** [comment]
The same thing is happening to me, have you found a solution?

**Comment by 1t3** [comment]
And how are you doing for the sawp from iot to helium?

**Comment by siong1987** [comment]
you should try to use the Phantom app directly instead of using the Phantom app within the Helium browser.

**Comment by paperphoton** [comment]
> you should try to use the Phantom app directly instead of using the Phantom app within the Helium browser.

Thank you for the contribution. However the problem here is that mostly the swap is needed for the IOT - HNT pair, which, I guess, is not present at the Phantom wallet.

**Comment by paperphoton** [comment]
> And how are you doing for the sawp from iot to helium?

You can still swap it via the Treasury swap. However, the liquidity there is far from being stable, so usually it's way more beneficial to swap via jup.ag

**Comment by KimPlaybit** [comment]
Did you find a solution to this?

I still have this exact problem.

**Comment by Talitrus** [comment]
@KimPlaybit , is the wallet connect button showing up at all? Are you getting a screen with just a cancel button?

**Comment by KimPlaybit** [comment]
@Talitrus i get to the jup.ag page, then after that i can't do anything. i click the "connect" up to the right, nothing happens, i click the "connect wallet" in the middle of the screen, nothing happens. there is no progress. 

i am also using a Redmi not 8 Pro.

**Comment by KimPlaybit** [comment]
Quick Update:
I am not able to use the docs.helium.com/helium-tokens/sol-token either. it wont let me connect my wallet here.

**Comment by paperphoton** [comment]
Another update from me:

In the latest version of the black app 2.1.0, the jup.ag page opened via the embedded browser has all the buttons broken: none of them is available for interaction. Besides, some captions are missing.

Dear developers, there is nothing wrong with admitting that the app has some issues on Redmi Note 8 pro devices. Closing the issue so prematurely was kind of rude.

**Comment by damasceno-dev** [comment]
For me, the connect button does not show up. Anybody have a clue on why this happens? I want to swap hnt for sol, and hnt is the only crypto I have on the Hellium Wallet

**Comment by Talitrus** [comment]
@damasceno-dev , if you send some SOL to your wallet from another wallet, does the problem still persist? I've heard of this happening when you run out of SOL.

**Comment by damasceno-dev** [comment]
@Talitrus I cant trade HNT for SOL using the swap utility either (https://docs.helium.com/helium-tokens/sol-token). Its the same issue, the connect button does not show up. But I'll try to send me some SOL as you suggested and give you the feedback.

**Comment by damasceno-dev** [comment]
@Talitrus it worked! Sending SOL to my wallet made the connect button appear! I was abble to connect my wallet and swap HNT for SOL.

Thank you very much!

**Comment by markodimitrije** [comment]
For me connecting to jup.ag using Helium mobile app from iPhone is not working for almost 2 weeks. Connect wallet button is available but connection is not established. I can also confirm it works perfectly well from Phantom app each time i try to connect. Further more i can;t connect to ASR rewards as well. 
App version i have installed is 2.8.2 (1721312163)
