### ISSUE TITLE
My device, which should be in the wallet, appears under another ID. The address my device should have is (HsMDB2ZcR44BpFrbWmupDhZgoy7Vi12fr8EVcgwoYfoz), but it is at the address (Htyv3uxqXcBLKujcku4jdK37JHPUzJmyMebtdbgForf8), which is not mine. This change was not made by me. How do I get my device back to my address?

### ISSUE THREAD

**Issue by pasalipomak** [helium/wallet-app#358]
![image](https://github.com/helium/wallet-app/assets/134585278/d4de08c7-7ffc-4fcb-a256-8402f9b5d748)
![image](https://github.com/helium/wallet-app/assets/134585278/94bbc6ac-d1c0-4795-bb2b-f878bd8bd68e)
![image](https://github.com/helium/wallet-app/assets/134585278/01cc074c-b2ba-479f-b9ee-9dd588649c5b)

**Comment by ChewingGlass** [comment]
https://explorer.solana.com/tx/2URF6qPPSEzyxHJfiswUwV3Nc8HuWtJPXX2c5RmW2dAUA85oWMy3i5CTkgsVXKfAKjShoSbNcyxqkBkbHhecht6n

This hotspot was transferred by HsMDB2ZcR44BpFrbWmupDhZgoy7Vi12fr8EVcgwoYfoz (who signed) to Htyv3uxqXcBLKujcku4jdK37JHPUzJmyMebtdbgForf8. There is no way for us to get it back. When you transfer an NFT, only the wallet you transferred it to can sign to transfer it back.
