### ISSUE TITLE
"Transfer" label may lead to unintended Hotspot transfers, suggest change

### ISSUE THREAD

**Issue by ke6jjj** [helium/wallet-app#360]
# Summary

Users may be accidentally transferring Hotspots to unusual wallets because of button proximity and ambiguous language. Changing the menu item label from "Transfer" to "Transfer Ownership" might be better.

# To Reproduce

1. Open the Wallet App and select a wallet with at least one Hotspot assigned to it.
2. Choose the collectables tab at the bottom of the screen (diamond).
3. Tap on a specific Hotspot to select it.
4. Notice that the screen shows two buttons below the Hotspot: **...** and **Claim Rewards**.
5. Tap **...** as if you _meant_ to tap **Claim Rewards**.
6. Notice that you are presented with a menu with two options, "Transfer" and "Copy hotspot key".
7. **STOP** -- Do not follow further directions from this point, they illustrate a possible misunderstanding.
22. Tap "Transfer" with the misunderstanding that you are _Transferring tokens_ from the claim. 
8. Enter in a custodial wallet address with the misunderstanding that sending your rewards to a specific address.
9. Lament that you have just transferred a Hotspot instead of tokens.

# Suggested change

For English, consider changing the localization of the `transfer` tag here:

<https://github.com/helium/wallet-app/blob/c2aa7f25fcfd4cb5f0dce976f94f23c5176df067/src/locales/en.ts#L163>

The best replacement for this specific instance would be `Transfer Hotspot`, but this particular tag is used for _all_ collectables, not just Hotspots. So in that light, `Transfer Ownership` might be the best short term choice.

**Comment by ChewingGlass** [comment]
This should be fixed now
