### ISSUE TITLE
My old address on my network that I seem Helium device. However, it does not seem to have that address on network Solano. The transfer process has been made by me are also in question. In my application I use the helium former address (14r89LXAzszgn1WnepbYKkGJJH1NFYgikfnujy8d 1dp7avs7u2x)While the device is still the same address as it appears on doesn't belong to me, I don't know who it belongs to or transfer to an address that appears to be there.

### ISSUE THREAD

**Issue by pasalipomak** [helium/wallet-app#362]

**Comment by ChewingGlass** [comment]
Not enough information here. Need screenshots and more description of what is happening, and what is expected.

**Comment by ChewingGlass** [comment]
You can't. I show you signing with the HsM address to transfer to Hty. You also transferred the hotspot from HsM to Hty. 

https://explorer.solana.com/tx/4StQWcWLLpSLMorju3XpetNJzMtMSPGKQ72MkG2N6XYQcdZTMEtxsnRGjWgAwGvdtRc4tYyQXUXqMPRmVRCAqLiV


We can't move anyone's devices for anyone else. This is all on the blockchain, only the holder of those private keys can do the transfer. If you don't have the private keys to Hty, why transfer devices to it?

**Comment by pasalipomak** [comment]
I did not transfer the device. I don't even know who owns this address. It's not even an address registered in my address book.

**Comment by ChewingGlass** [comment]
All I have to go off of is the transaction history, which show that someone with your private keys did this transfer. Maybe someone compromised your keys?

**Comment by pasalipomak** [comment]
It happened after the new implementation. I had no problems with the old application. I only have 12 words. nobody else knows. Could there be a gap in the application?

**Comment by ChewingGlass** [comment]
@Perronef5 could speak more to this, but there's no way for the seed phrase to leave the device, save for you exporting it. 

The only way for those transfers to have happened would be if you physically used the app and did a transfer. Which all the evidence here suggests. Unfortunately there's not much I can do beyond that. The NFTs have been moved, and they are with the wallet they were transferred to. We don't have the ability to transfer hotspots from other wallets.

**Comment by pasalipomak** [comment]
What a pity. I've spent so much time and money on this project. The result was not supposed to be like this. If I had really done this process, I wouldn't have bothered at all, but the device was transferred to another account before I did it.
