### ISSUE TITLE
Unable to transfer due to number notation issue with decimals.

### ISSUE THREAD

**Issue by fruitmans** [helium/wallet-app#364]
I am unable to transfer tokens since the app messes up all number notations using "," and "." differently on multiple pages. This results in an insufficient funds notification and the transfer fails. I try to transfer all my tokens with the "max" button for the amount. 

I was unable to take and add screenshots since the app prevents this from happening. 

My phone is an Google Pixel 2XL
I run the latest version of the helium app available in the store to me V2.0.8
The language of my phone is set to Dutch which could trigger the issue.

**Comment by fruitmans** [comment]
[](url)
![DSC05725](https://github.com/helium/wallet-app/assets/11027774/f4f4fce6-e2eb-4690-8787-9ab6b7421acb)
![DSC05726](https://github.com/helium/wallet-app/assets/11027774/8fa06e8f-da1d-443a-b18d-15eab317abd3)
![DSC05727](https://github.com/helium/wallet-app/assets/11027774/2f9a205d-47ad-43e3-a2c6-c9ef057df487)
![DSC05729](https://github.com/helium/wallet-app/assets/11027774/06dd83e2-5fe4-48a7-84ad-13bd5ad917c9)
![DSC05730](https://github.com/helium/wallet-app/assets/11027774/9b0cbee7-3874-4ed3-a924-7a45beb60df0)
![DSC05731](https://github.com/helium/wallet-app/assets/11027774/6c9ba973-7261-435c-863b-f59c6418d6ff)

**Comment by ChewingGlass** [comment]
@fruitmans how much sol do you have in your wallet? I'm not sure this is a commas issue

**Comment by fruitmans** [comment]
At this moment I have 0.00262176 SOL in my wallet so I thing that should be enough for the transfer. I (of  course) am also not sure that comma’s are the cause of my problem but notices the inconsistent presentation of the numbers in the app. The account I want to transfer the IOT too is an account linked to my ledger hardware wallet. I don’t know why it should matter but it might be a piece to solve the puzzle 😉

 

Van: Noah Prince ***@***.***> 
Verzonden: dinsdag 6 juni 2023 18:30
Aan: helium/wallet-app ***@***.***>
CC: fruitmans ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [helium/wallet-app] Unable to transfer due to number notation issue with decimals. (Issue #364)

 

@fruitmans <https://github.com/fruitmans>  how much sol do you have in your wallet? I'm not sure this is a commas issue

**Comment by ChewingGlass** [comment]
0.00262176 sol may not be enough to do a transfer due to the need to create an associated token account. Can you try it with 0.02 sol at least?

**Comment by fruitmans** [comment]
Woehoe! You are the best :-) This indeed solved my issue. Maybe there is a way to make the failure notification a bit more specific towards a optional solution. For now my issue is solved so i am happy. Thanks!
