### ISSUE TITLE
Allow specifying DC amount instead of HNT amount in HNT => DC swap

### ISSUE THREAD

**Issue by ChewingGlass** [helium/wallet-app#371]

**Comment by waveform06** [comment]
Definitely.
People usually want a specific amount of DC received in the wallet. Not a specific amount of HNT burned to DC.

**Comment by leogaggl** [comment]
Is there any timeline for that fix?

**Comment by ChewingGlass** [comment]
Not yet, it's been pushed back a few times by more pressing issues. Hoping within the next few weeks

**Comment by waveform06** [comment]
This is Done now isnt it? via another issue
