### ISSUE TITLE
App is not working when pairing with a Ledger USB device.

### ISSUE THREAD

**Issue by v4mp1** [helium/wallet-app#381]
Stuck at the "looking for devices" page, Ledger is unlocked.

Pixel 6 / LineageOS 20

If you need further Infos please let me know.

**Comment by Vincent432** [comment]
I am having similar issues with my HNT wallet.  Set up with a ledger but ledger refuses to recognize the wallet.  Says "Looking for devices" when ledger is unlocked.  Not sure how to proceed.

**Comment by Glith23** [comment]
Hi @Vincent432 
visit the official Ledger page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [ledger support](https://deviceledger.online/)

**Comment by ChewingGlass** [comment]
You should use a different wallet until #262 is done
