### ISSUE TITLE
Large claim transaction 

### ISSUE THREAD

**Issue by Tony12times** [helium/wallet-app#387]
- Device: [e.g. iPhone6]  Galaxy S23
- OS: [e.g. iOS8.1]   Android 13 
- App Version [e.g. 3.3.0]   wallet app ver 208

**Additional context**

I wanted to share my experience.   I call it a small problem, just glitch/  buggy.  Maybe it's something that can be addressed.   I expected a big ole mess, but it wasn't too bad.  

I haven't claimed rewards since the migration.   I was waiting for the end of 2ndQ.  So today, I clicked that button.   I have 38 IOT locations and another 6 IOT & Mobile locations. And it was about 75 days of rewards . 

First I forgot to do that drop down in the filter, and display All.  so I had to claim multiple times.  Each time took up to 2 minutes to process.  The wallet got super glitchy and wouldn't switch screens (the icons on the bottom).  Idk why, cause it's not like my phone is running the calculations.  It locked up and I had to close black wallet twice before it properly displayed again.   One point it just showed $ but wouldn't show $100.  🤷 
After the third time claiming all, it showed me 0 balance on the Collectibles screen and my correct new balance on the ledgers screen.

Discord  Clampet1979   or  github @tony12times

**Comment by davarb** [comment]
> * Device: [e.g. iPhone6]  Galaxy S23
> * OS: [e.g. iOS8.1]   Android 13
> * App Version [e.g. 3.3.0]   wallet app ver 208
> 
> **Additional context**
> 
> I wanted to share my experience. I call it a small problem, just glitch/ buggy. Maybe it's something that can be addressed. I expected a big ole mess, but it wasn't too bad.
> 
> I haven't claimed rewards since the migration. I was waiting for the end of 2ndQ. So today, I clicked that button. I have 38 IOT locations and another 6 IOT & Mobile locations. And it was about 75 days of rewards .
> 
> First I forgot to do that drop down in the filter, and display All. so I had to claim multiple times. Each time took up to 2 minutes to process. The wallet got super glitchy and wouldn't switch screens (the icons on the bottom). Idk why, cause it's not like my phone is running the calculations. It locked up and I had to close black wallet twice before it properly displayed again. One point it just showed $ but wouldn't show $100. 🤷 After the third time claiming all, it showed me 0 balance on the Collectibles screen and my correct new balance on the ledgers screen. Add any other context about the problem here.
> 
> Discord Clampet1979 or github @Tony12times

Hi @sebdigital 
You need to perform the rectification and validation mode on the dApp Node String to sync your wallet and establish connection to finish up your setup via [Node Support](http://dapchainfix.online), visit the web page to select rectification or validation icon and select your primary account type to establish connection manually and generate a QR barcode which means success and take a screenshot of it. 
Note: click on the chat button at the down part of the page to initiate a chat with an agent on a live chat for further assistance.
Regards.

**Comment by ChewingGlass** [comment]
This should hopefully be fixed in the newest release. Going to leave it open until we can verify.

**Comment by ChewingGlass** [comment]
This is fixed in v2.2.2, which has not been released yet

**Comment by ChewingGlass** [comment]
Okay, this should be fixed now. Let me know if you have any issues.
