### ISSUE TITLE
Android 2.0.9 transaction history not shown

### ISSUE THREAD

**Issue by Sophi** [helium/wallet-app#392]
**Describe the bug**
Activity is blank in the All activity section under the token type.
Android 2.0.9

**To Reproduce**
Open app
Click the white $ icon on the lowest left
-you should see your total token in $ (my settings are on $USD) on this screen
Click on any option on lower half of screen: HNT, SOL, IOT, MOBILE 
I clicked on HNT
On this screen is the amount of HNT on the top half and an Activity section.
The activity section shows All activity on the left and Filter on the right

**Expected behavior**
Expected to see previous activity on the activity / filter area

**Screenshots**

![screenshot](https://github.com/helium/wallet-app/assets/1236607/28421691-52cf-455b-895d-b132a376cd0b)

**Smartphone (please complete the following information):**

- Device: Pixel 6
- OS: Android 13
- App Version 2.0.9

**Comment by ChewingGlass** [comment]
fixed this
