### ISSUE TITLE
bug: able to wipe a wallet without a warning 

### ISSUE THREAD

**Issue by nosmaster89** [helium/wallet-app#396]
**Describe the bug**
when adding a new wallet to the app if you use the same name as a existing wallet it will override the wallet with that name
**To Reproduce**

create a wallet called x 
import a new wallet and call this one x it will override the first one without asking for confirmation
**Expected behavior**
i would expect the same warning as removing the wallet from the app
**Screenshots**
cant screenshot on android
**Smartphone (please complete the following information):**

- Device: [e.g. mi 11]
- OS: [e.g.android 13]
- App Version [e.g. 2.0.8]

**Comment by bryzettler** [comment]
Was unable to recreate, was able to have two wallets with the same name
