### ISSUE TITLE
No SOL, and swap utility dosent work.

### ISSUE THREAD

**Issue by DyggiPrahl** [helium/wallet-app#399]
**Describe the Bug
When trying to convert helium to Sol in the Swap Utility it keeps loading and dosent complete the transaction. And can't transfere from other wallet. Have SOL on crypto.com but unable to transfere. 
**To Reproduce**

1. Go to 'Globe on bottum bar'
2. Click on 'link to sol token'
3. Scroll down to 'swap utility after connection wallet and it keeps on loading. 

**Expected behavior**
A few seconds of loading and then SOL transfere would complete.

**Screenshots**

**Smartphone (please complete the following information):**

- Device: S22 Ultra
- OS: Android 13
- App Version [2.0.8]

**Additional context**

**Comment by waveform06** [comment]
How much SOL do you have in your Helium Wallet?

**Comment by DyggiPrahl** [comment]
About 0.00089, so after what I have found enuff, but on the limit.

**Comment by waveform06** [comment]
Thats not enough, you need to transfer some from outside the wallet into the wallet
In the Wallet App, goto Settings / Copy Address / Solana and transfer to that from Crypto.com

**Comment by DyggiPrahl** [comment]
OK, so managed to do it, but not using mobile but web browser. For some reason the 2 apps don't want to send any SOL, but when I Crypto.com on browser, it ends up in the Helium Wallet.

Cheers
