### ISSUE TITLE
First access of location assert screen does not show correct location.

### ISSUE THREAD

**Issue by waveform06** [helium/wallet-app#400]
The correct location of the hotspot is not shown when first going to location assert screen

Goto a hotspot that you have never gone to the location assert screen before and manage / location assert, select IOT and the default location it shows is SF
Go back to manage and press location assert again, the IOT and it shows the correct hotspot location with the green dot. 
Reboot of phone sometimes seems to clear the correct location and you need to do this again
Sometimes it does not

On Android 12

**Comment by ChewingGlass** [comment]
Fixed in latest release on testfliht
