### ISSUE TITLE
Asserting Location of hotspot requires more than 0.000005 SOL

### ISSUE THREAD

**Issue by fidian** [helium/wallet-app#404]
**Describe the bug**
The screen states it needs 0.000005 SOL. 500k DC is also needed.

**To Reproduce**

1. Start the process to assert the location of a hotspot.

**Expected behavior**
All fees are displayed on the screen.

**Screenshots**
Screenshots are not able to be made on Android.

**Smartphone (please complete the following information):**

- Device: OneTouch 7 Pro
- OS: Android 12
- App Version 2.1.0

**Additional context**
I'm unsure about the 500k DC; I only heard about it through the very fast support in Discord.

**Comment by ChewingGlass** [comment]
Closed because this is the expected behavior
