### ISSUE TITLE
Clarify Antenna Gain & Elevation configuration UI

### ISSUE THREAD

**Issue by jthiller** [helium/wallet-app#405]
**Describe the bug**
After selecting location for reassert, UI prompts for height/gain updates in unlabeled UI.

**Expected behavior**
UI should clearly indicate which fields are used for which values.

**Screenshots**
![IMG_3509](https://github.com/helium/wallet-app/assets/1965053/c4e6f696-818b-4a11-a206-57e459b9efd5)

**Smartphone (please complete the following information):**

- Device: iPhone 14 Pro
- OS: 16.6
- App Version: 2.1.1

**Comment by ChewingGlass** [comment]
Should be fixed now
