### ISSUE TITLE
Update Treasury Swap warning 

### ISSUE THREAD

**Issue by waveform06** [helium/wallet-app#409]
**Describe the bug**
The Treasury Swap Warning says it's only been a few days since the migration
Its now over 100 and after the halving which will slow down the exponential changes.

**To Reproduce**
Try to swap any tokens

**Expected behavior**
Change to say a few weeks/months or say this is the floor exchange value and preferential rates may be obtained at exchanges or aggregators

**Comment by ChewingGlass** [comment]
This will be fixed by #437 . That will give the best rates and no need for a warning.
