### ISSUE TITLE
Burn HNT -> DC screens need to support solana

### ISSUE THREAD

**Issue by Perronef5** [helium/wallet-app#42]
Burn HNT to DC screens should support Solana.

**Comment by lytzV** [comment]
When switched to Solana, instead of an origin wallet burning HNT into DC towards the destination wallet, what happens is the origin wallet holds the DC but only delegates it to the destination wallet.

**Comment by lytzV** [comment]
@dannpl are you interested in taking this on?

**Comment by lytzV** [comment]
Lovely! I'll follow up w/ more detail describing the feature by EOW

**Comment by lytzV** [comment]
@dannpl 

## Timeline
This is a critical feature for the L1 transition that needs be completed & tested by 02/24/2023

## Users
Any person that may want to mint & delegate Data Credits, which could include LNS (LoRaWAN Network Server) operators, roaming partners, their customers or any person executing this transaction on their behalf

## User Flow
Most of the UI is there already, just need to repurpose them so they are compatible with the Solana narrative
See [Figma Prototype here](https://www.figma.com/proto/5kFEOY57EDTobBxKLlZNN6/Untitled?node-id=1%3A14&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A14)

## Appendix
[A primer on Solana Programming by Noah](https://github.com/helium/docs/blob/78d6fb6a9e34294b1dea8335e153b7b28a1231a5/docs/solana/primer.mdx)

Let me know if you have questions or need more context. We can sync over a call as well.

**Comment by dannpl** [comment]
Heyy, thank you very much for these updates. @lytzV

**Comment by lytzV** [comment]
@dannpl any questions about the user flow? 

let's set up a weekly sync starting next week, what time works best for you?

**Comment by dannpl** [comment]
Heyy, for now no doubt, I'm going to finish #99 today and I'll start this one.

I think 16:00~16:30 WET.

**Comment by lytzV** [comment]
Just sent you a friend request on Discord!

**Comment by dannpl** [comment]
Hy, I lost access to figma!

And my wallet needed to be present here in betaAccess to show the menu.
<img width="1111" alt="Screenshot 2023-02-02 at 13 06 34" src="https://user-images.githubusercontent.com/37663993/216333058-7778665e-7ea2-41af-a059-892d2453d6ba.png">

<img width="424" alt="Screenshot 2023-02-02 at 13 05 36" src="https://user-images.githubusercontent.com/37663993/216332898-bf42e549-bedf-4e90-a1ca-ccfe7c2e9ea8.png">

Without these things it's hard to help

**Comment by cokes518** [comment]
Send me your email and I’ll reinvite you.
________________________________

**Comment by Perronef5** [comment]
So spoke to @lytzV & @dannpl offline and we agreed the experience should be as follows:

1. User navigates to swap screen and swaps HNT -> DC by calling the `mintDataCredits` function as was done for xNFT here https://github.com/helium/helium-program-library/blob/master/packages/xnft-hotspot/src/components/screens/Swap/Swap.tsx#L55
2. User now has DC in wallet. User then navigates to account token list and clicks on DC token.
3. User now has two options: user can click QR code button to scan a QR code that pre-populates Delegate screen or user can click on delegate button.
4. Finally, user is on the swipe to delegate screen and either has the screen pre-populate via QR code scan or needs to manually fill in recipient address and DC to delegate.

**Comment by lytzV** [comment]
btw now that we are separating mint & delegate -- there will be a scenario where the user tries to delegate more than what he/she has minted. There should be an error message that prompts the user to mint more DC.
