### ISSUE TITLE
Wallet Connect only shows 'cancel' button when insufficient SOL

### ISSUE THREAD

**Issue by Talitrus** [helium/wallet-app#422]
When connecting the Helium Wallet to a dApp, the current logic hides the Connect button if the user has insufficient SOL. Users should still be allowed to connect even if they do not have enough SOL.

**Comment by ChewingGlass** [comment]
This should be fixed in the latest release!

**Comment by ChewingGlass** [comment]
(on testflight right now, will go live soon)
