### ISSUE TITLE
Convert to Sol modal presents terrifying number.

### ISSUE THREAD

**Issue by jthiller** [helium/wallet-app#442]
**Describe the bug**
Modal to convert HNT to SOL seems to be missing a decimal

![image](https://github.com/helium/wallet-app/assets/1965053/3e7da6f1-a500-4fb9-ac67-6c0efe554d44)

**To Reproduce**

1. have not enough sol
2. claim rewards

- Device: [e.g. iPhone14]
- App Version v2.2.0

**Comment by ChewingGlass** [comment]
This will be fixed when the Jupiter swap goes live, it's in that PR.
