### ISSUE TITLE
Can´t connect my Helium wallet to Swap Utility

### ISSUE THREAD

**Issue by Gerbilwaster** [helium/wallet-app#453]
**Describe the bug**
When trying to use the Swap Utility, I can't connect to my helium Wallet.

I press Select Wallet, I select Helium Wallet wich appears as detected but then I don't have an Accept button, only Cancel.

**Smartphone (please complete the following information):**

- Device: Oneplus 8T
- OS: 13
- App Version v2.1.0

![1](https://github.com/helium/wallet-app/assets/144676299/8c8ca8bf-9ee5-404d-8a68-62751895e341)
![2](https://github.com/helium/wallet-app/assets/144676299/6249298d-1316-4d24-9034-59a4117d0681)

**Comment by ChewingGlass** [comment]
This should be fixed in v2.2.0+
