### ISSUE TITLE
Feature Request: Display the amount of staked HNTs

### ISSUE THREAD

**Issue by dejjjen** [helium/wallet-app#456]
**Describe the bug**
In my wallet, any tokens staked or on an order, will not be counted in the amount in the first tab

**To Reproduce**

1. Go to the $ tab
The HNT amount says 0 HNT even if I have staked HNTs

**Expected behavior**
I would expect the amount of staked HNT to be available in this tab in order to see the full Portfolio balance of tokens/staked tokens

**Smartphone (please complete the following information):**

- Device: [iPhone 12 Pro]

**Comment by ChewingGlass** [comment]
The wallet app currently doesn't support veHNT positions. Closing because this will be added in #402
