### ISSUE TITLE
Display address for HMH

### ISSUE THREAD

**Issue by lxie123** [helium/wallet-app#458]
For HMH, current location is missing in the hotspot view.  It needs to be added

**Comment by ChewingGlass** [comment]
I believe #467 is addressing this

**Comment by abhay** [comment]
Since this was reverted, let’s reprioritize.

**Comment by ChewingGlass** [comment]
There's a series of features that will close this. #472, https://github.com/helium/helium-program-library/issues/436, and then finally this issue

**Comment by ChewingGlass** [comment]
This is done
