### ISSUE TITLE
Remove Helium from Share Address Menu

### ISSUE THREAD

**Issue by Ryan-Goldstein** [helium/wallet-app#463]
A large number of users on the Helium Discord, Reddit, and elsewhere have expressed confusion and frustration for months due to selecting 'Helium' as the address to copy for receiving HNT, and having exchanges and other entities report that it's an invalid address.

I'm unaware of any benefit of keeping the legacy Helium address there, so I'm proposing simplifying Settings by removing `Share Address` entirely (as `Copy Address` serves the same purpose when there's only one item available for selection in `Share Address`).

**Comment by EricAndreasson** [comment]
Completely agree.
It's confusing some people when they're trying to complete transactions with HNT.
They believe they must use the Helium Address because HNT is a "Helium token".
