### ISSUE TITLE
BLE Config: Error message for already-onboarded Hotspot unclear.

### ISSUE THREAD

**Issue by jthiller** [helium/wallet-app#483]
The error message for an already-onboarded Hotspot doesn't match the action the user should be taking.

Ideally we look up whether the Hotspot is onboarded, reiterate the animal name and possibly the owner, then let the user move to the next step (assert).

<kbd><img src="https://github.com/helium/wallet-app/assets/1965053/b7f5e896-a711-47f5-9903-2748fd9b69d7" width="50%"></kbd>

**Comment by ChewingGlass** [comment]
This error is correct, that hotspot wasn't in the onboarding server.
