### ISSUE TITLE
Bug when creating a wallet and selecting the words

### ISSUE THREAD

**Issue by dannpl** [helium/wallet-app#51]
**Bug**
When selecting my words when creating a wallet, the words are blank

**To Reproduce**

1. Go to create an new wallet
2. Minimize the APP and back to the app

**Screenshots**
https://user-images.githubusercontent.com/37663993/204056513-21b5de45-229e-4ebb-a21c-d66f73fe1dd8.mp4

**Smartphone:**
- Device: Iphone 11
- OS: IOS16
- App Version: last

**Comment by dannpl** [comment]
Yes, i can fix it's @Perronef5 ?

**Comment by Perronef5** [comment]
Yes I don't see any problem with that. @cokes518 Cool if @dannpl fixes this bug?

**Comment by cokes518** [comment]
Works for me. Good luck!
________________________________
