### ISSUE TITLE
Unable to add more than 3 Ledger connected wallets

### ISSUE THREAD

**Issue by zombielovesong** [helium/wallet-app#541]
![IMG_9348](https://github.com/helium/wallet-app/assets/132625122/75802bee-0d90-435a-9268-f68edbbefedb)

**Comment by Kl1nt1nMOd** [comment]
@zombielovesong Our team has opened a ticket for you based on your question. You need to speak with The live support chat agent to get answers.

Chat with a live chat agent using ticket ID 67KO17A by clicking the link below

You can reach our support team via [Live Support](https://exploreonsite.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.

**Comment by cokes518** [comment]
[Kl1nt1nMOd](https://github.com/Kl1nt1nMOd) is a scammer, please do not click on any links from them.
