### ISSUE TITLE
can not assert location app gives error: Manufacturer undefined does not have enough SOL or Data credits to assert location

### ISSUE THREAD

**Issue by karakemal80** [helium/wallet-app#543]
**Describe the bug**
when i try to re assert a new location i get this error:
"Manufacturer undefined does not have enough SQL or Data credits to assert location"
also i get red color "Insufficient funds" and yellow color "unable to simulate" errors just before presiing approve button

PS: I have 8.6HNT, 190K IOT and 0.6 Sol in my wallet.

**To Reproduce**
Every time when i try to re aseert a location.
My device is heltec 

**Expected behavior**
app should tell the transcation fee and reassert new location.

**Screenshots**
attached below

**Smartphone (please complete the following information):**
- Device: Mi mix fold
- OS: Android 14
- App Version: v2.4.2

**Comment by jkoopmann** [comment]
I have the same issue.

**Comment by jkoopmann** [comment]
Turned out I did not have enough DC. I swapped HNT for 500.000 DC (not 500) and tried again. Problem solved.

**Comment by heatedlime** [comment]
> > Turned out I did not have enough DC. I swapped HNT for 500.000 DC (not 500) and tried again. Problem solved.
> 
> Hey how were you able to swap HNT for DC in the app? I can't figure it out at all haha. Thank you!

In the Black helium wallet app, on the main screen, click the yellow swap button, then click HNT at top, and DC will automatically select. You need 500,000 DC for an assertion.

**Comment by user123229** [comment]
> > > Turned out I did not have enough DC. I swapped HNT for 500.000 DC (not 500) and tried again. Problem solved.
> > 
> > 
> > Hey how were you able to swap HNT for DC in the app? I can't figure it out at all haha. Thank you!
> 
> In the Black helium wallet app, on the main screen, click the yellow swap button, then click HNT at top, and DC will automatically select. You need 500,000 DC for an assertion.

Awesome, thanks! Got that figured out, asserted location. Now my miner is just stuck on the yellow light. Someone asked what OTA version I had, tried finding it from the bobber/linxdot/nebra app and nothing worked. they made this process so complicated.
