### ISSUE TITLE
Accidently (transferred) "Minted" my hotspot to my coinbase on the Solana Network

### ISSUE THREAD

**Issue by tommyziegler2003** [helium/wallet-app#545]
Hello ,
I accidentally (transferred) minted my hotspot to my coinbase Solana network thinking that it would mine to that network, however I don't see it on the coinbase wallet side.   Is there anyway to undo what I did or have any tips on what I can do?  I'd like to get my miner running correctly again.

Here is the transaction:

https://explorer.solana.com/tx/5NCWBrG6wfGmqQAp1kRfnEsGBf9D18xFN2dtYvazQZZmnVkx4KLTMkYQsBz6aJ2WxF4gxzExv3oMSpE4yzvLDypM?cluster=mainnet-beta

Android app : Helium Wallet v2.4.2

Thanks,
Tommy

**Comment by ChewingGlass** [comment]
Unfortunately there is no way to fix this but to have the destination wallet transfer it back to you.

If the destination wallet is a coinbase self-custody wallet, you should be able to export the seed phrase and import it into a wallet like Solflare or Phantom that supports compressed NFTs. You can then go to the NFTs tab and transfer it back to your Helium Wallet.

If the wallet is not a self-custody wallet and just an exchange wallet, you will need to contact coinbase customer service and ask them to transfer the hotspot back to you. Though I am not sure if they will do this, I don't know of anyone that has tried to get coinbase to transfer back a cNFT.

**Comment by tommyziegler2003** [comment]
And factory resetting the helium miner won't work either right?Thanks,Tommy
-------- Original message --------From: Noah Prince ***@***.***> Date: 11/27/23  9:18 AM  (GMT-08:00) To: helium/wallet-app ***@***.***> Cc: tommyziegler2003 ***@***.***>, Author ***@***.***> Subject: Re: [helium/wallet-app] Accidently (transferred) "Minted" my hotspot to my coinbase on the Solana Network (Issue #545) 
Unfortunately there is no way to fix this but to have the destination wallet transfer it back to you.
If the destination wallet is a coinbase self-custody wallet, you should be able to export the seed phrase and import it into a wallet like Solflare or Phantom that supports compressed NFTs. You can then go to the NFTs tab and transfer it back to your Helium Wallet.
If the wallet is not a self-custody wallet and just an exchange wallet, you will need to contact coinbase customer service and ask them to transfer the hotspot back to you. Though I am not sure if they will do this, I don't know of anyone that has tried to get coinbase to transfer back a cNFT.

**Comment by ChewingGlass** [comment]
No, factory reset won't do it. Each miner has a crytographic private key installed that is it's "identity." Your miner already has an identity on chain. I think there may be ways to reroll this private key but I'm sure it depends on the manufacturer and is not straightforward to accomplish. Better bet is to have coinbase send it back.

**Comment by tommyziegler2003** [comment]
Ya , so far Coinbase has been no help at all. This was their response:

> Currently, our marketplace only supports transactions on Ethereum with NFTs built using Ethereum's ERC 721 and 1155 standards. Be sure to only send this type of NFT to your account for now. We are currently working on supporting transactions on multiple blockchains. I can see that your funds has been completed on the blockchain, so in this case we are not able to recover or reverse these funds.

....

> We are not supporting Solana network for NFT so your NFT are stuck on the Solana blockchain.

I'm going to try to contact someone who manages the Solana network, but so far it seems its just a public community.

**Comment by tommyziegler2003** [comment]
Following up... So far I'm not able to reach anyone from Solana.  I might have better luck just getting another miner.  I've also reached out to the Bobcat miner support if they can re-flash my device, but there has been no response.

**Comment by ChewingGlass** [comment]
Shame that coinbase can't just send it back to you, that's the ideal solution. Sorry this happened

**Comment by ChewingGlass** [comment]
Closing this issue, unfortunately we can't control Coinbase's wallet or practices.
