### ISSUE TITLE
Using payment links from the Payment Request is missing the address

### ISSUE THREAD

**Issue by KnightAR** [helium/wallet-app#549]
**Describe the bug**
Using payment links from the Payment Request is missing the address

**To Reproduce**

1. Go to the payment link: [https://wallet.helium.com/payment?payee=ETgqoB3d2XZQyqywoYiD9Y4NLEJbyVa1MLAJzrduht9D&amount=100000000&memo=&mint=hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux](https://wallet.helium.com/payment?payee=ETgqoB3d2XZQyqywoYiD9Y4NLEJbyVa1MLAJzrduht9D&amount=100000000&memo=&mint=hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux) on your device with the Helium Wallet app installed.
2. The address field is blank, the amount is enters fine but the address is blank.

**Expected behavior**
The address and amount should be filled in

**Smartphone:**

- Device: Samsung Galaxy S22 Ultra
- OS: Android 13
- App Version: v2.4.2 (1700062404)

This is a recent issue, 2 months ago I used the same feature and it entered both fields without an issue.

**Comment by ChewingGlass** [comment]
Seems to be working now. Closing the issue.
