### ISSUE TITLE
App unlock PIN code length does not match system pin code length preventing unlock of app

### ISSUE THREAD

**Issue by AMSint** [helium/wallet-app#551]
**Describe the bug**
The length of pin codes supported by the app appears to not properly adapt to the settings within the android OS when using a PIN code longer than 6 digits. 

**To Reproduce**
1. On an android device with an 8 digit pin length, install the Helium Wallet app.
2. Attempt to enter the device PIN code to unlock the app
3. Observe that the app only shows six digit marker circles and declares failure on the entry of the sixth digit.

**Expected behavior**
The app should support PIN lengths on android up to 16 digits.

**Smartphone (please complete the following information):**
Pixel 7a running android 14

**Comment by ChewingGlass** [comment]
The wallet app uses the PIN you set for the wallet app, not the android system. Try using the PIN you originally set up for the app.

**Comment by AMSint** [comment]
Confirmed. I misread the prompt (mentally inserted current device pin). Not a bug, should be closed.
