### ISSUE TITLE
Minor currency symbol bug

### ISSUE THREAD

**Issue by maurobusso** [helium/wallet-app#592]
**Describe the bug**
My value is set to GBP however in the home page at the top where the current prices of the crypto currencies are, the float value is the correct GBP price but the symbol shown is $

**Expected behavior**
It should be £

**Smartphone **
- Device: Xiaomi Redmi Note 9
- OS: Android 12
- App Version 2.5.7

**Comment by ChewingGlass** [comment]
I'm not able to reproduce this

**Comment by maurobusso** [comment]
They have been removed altogether, I think.
