### ISSUE TITLE
Text alignment seems to be off 

### ISSUE THREAD

**Issue by maurobusso** [helium/wallet-app#593]
**Describe the bug**
Text is not properly centred and overlap at the top of the screen

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'main page'
2. Click on 'swap'
3. Click on 'slippage'

**Expected behaviour**
The text could be centred a bit more

**Smartphone **
Device: Xiaomi Redmi Note 9
OS: Android 12
App Version 2.5.7

**Comment by ChewingGlass** [comment]
Looks perfectly centered to me
![simulator_screenshot_536353D1-F9A5-4956-9F27-875EBE0750BE](https://github.com/helium/wallet-app/assets/83885631/4e96b0b0-4bcf-458d-b324-03373ef0fe59)

**Comment by maurobusso** [comment]
It is not on my device, which view port size is 393 x 873. 
![IMG-20240409-WA0001](https://github.com/helium/wallet-app/assets/107254152/f8fc3b25-3428-4816-8535-2e5666ea24ca)

**Comment by ChewingGlass** [comment]
Woah, that vertical centering is odd.

**Comment by ChewingGlass** [comment]
Will be fixed in the next release. Thanks for reporting!
