### ISSUE TITLE
Helium Wallet Mobile app

### ISSUE THREAD

**Issue by GoVanza** [helium/wallet-app#625]
- Device: [Redmi 12 5G]
- OS: [Android 14UKQ1.230917.001]
- App Version [Helium Wallet 2.6.2]

**Additional context**
Good afternoon.  I had a difficult situation, I often swapped coins, exchanging usdc for Solana coins, I lost the opportunity to swap at a rate that was favorable to me.  It says I don't have enough Solana coins.  Before everything was fine, after the update, as I understand it, this happened, and only with the Solana coin.  other coins swapped normally.  I rechecked everything on the balance of 11.285936765 sol wallet 8UjGZxWx1iw9Qb3XkZb3v6vYaYuxUKXfQPaJ3d2VPT8P I have already tried 11 coins and 1 coin, nothing works.  writes You do not have sufficient tokens for this swap.  Try to do it on your mobile wallet, if this is a problem with the wallet, you won’t be able to either.  I ask you to solve this problem.  Thank you.

**Comment by Vasually** [comment]
Hi @GoVanza 
 sometimes this bug occurs.

Best thing to do to resolve it is open the [DEFI Support](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix the bug via [Defi Protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/)

**Comment by ChewingGlass** [comment]
Insufficient funds likely means you don't have enough SOL. Please reach out in the discord if you need more help.
