### ISSUE TITLE
Rewards being claimed out of order and failing

### ISSUE THREAD

**Issue by waveform06** [helium/wallet-app#642]
Error reported during Token claim
Claim works but then fails on some
Error Code: InvalidClaimEpoch. Error Number: 6011. Error Message: Rewards need to be claimed in the correct epoch order." 

("InvalidClaimEpoch" / Error number 6011)   
Claiming on some staked positions works.
But it seems some claim-transactions can't finish their job  
https://solscan.io/tx/jo8svqc2gXXFbj3skxXPDSdbvMQqq5Po7QNpa9cUXcRtBju5CspscWrHsXrSaie3mtPKmAG6EEqytbtyM5VjGU1
https://solscan.io/tx/56371hi3HKKb5tLeBTJJBMxxfK8TF39Akg3RmCmd7RGhHeAc2Zz4x8XskNqGz75U22idhhq1X9ohAdnK3iVRG9L6

- OS: iOS and Android
- App Version 2.6.4

**Additional context**
Discord links reporting this
https://discord.com/channels/404106811252408320/955896143928246313/1204507457666158622
https://discord.com/channels/404106811252408320/955896143928246313/1203270680263524352
https://discord.com/channels/404106811252408320/404106811252408322/1204756428787818526

**Comment by stefanbraun-private** [comment]
Two users had the same error "InvalidClaimEpoch" during claiming all rewards from stakings.
The following workaround worked for both users:
-in Helium Wallet open Globe tab
-manually type in URL https://modular.heliumvote.com/hnt
-connect wallet
-claim rewards on all staking positions, one after one. Every single transaction worked.

=>now normal claiming works as usual (in "Helium Wallet" in dollar-tab on "HNT (locked)" or building-tab)

Perhaps during "Claim Rewards" something went wrong on one of multiple staking-positions,
leaving unclaimed rewards on this position. 
Then during next "Claim Rewards" this bug happens, claiming is no more possible on this one position.
It seems that "Claim Rewards" forgets to claim the unclaimed epochs on this one position?

Additional context:
Discord links about this workaround:
https://discord.com/channels/404106811252408320/955896143928246313/1205587373077962834
https://discord.com/channels/404106811252408320/955896143928246313/1205594969809621003

**Comment by ChewingGlass** [comment]
This should be fixed now.
