### ISSUE TITLE
Can't claim rewards (have .02 sol in wallet)

### ISSUE THREAD

**Issue by synfidel** [helium/wallet-app#652]
**Describe the bug**
I am unable to claim the rewards from my gateway.  Any time I hit the claim rewards button I get the following message:  "Reward Redemption failed.  Please try again later.  (request failed with status code 404).  I've tried many times over the past two weeks with the same result.  I hadn't claimed rewards in months, so I'm not sure when this might have started.  

**To Reproduce**

1. Go to Collectibles
2. Click on Claim Rewards > Add all to account
3. Scroll down to ......  No need to scroll error pops up here
4. See error:   Reward Redemption failed.  Please try again later.  (request failed with status code 404)

**Expected behavior**
I expected the rewards to be moved into my wallet

**Screenshots**
For some reason, when I take a screenshot it shows up as all black (assuming security feature)

**Smartphone (please complete the following information):**

- Device: Pixel 7 Pro
- App Version:  2.6.4 (1706742520) -- I do see an update announcement within the app, but see no update option in play store
- *Additional context**

**Comment by synfidel** [comment]
Going to settings , App, helium wallet then clear cache resolved my issue

**Comment by ChewingGlass** [comment]
This should be fixed in later releases. 2.7.0+
