### ISSUE TITLE
Can't get my money back from the wallet !

### ISSUE THREAD

**Issue by domibe** [helium/wallet-app#654]
**Describe the bug**
Can't send my Solana to another wallet or cryptocurrency exchange

**To Reproduce**

1. Go to you wallet and clik on Solana
2. Click on Send
3. Paste the addres and clik on Max in eneter Sol Amount
4. Clik on Pay
5. Swipe to Send SOL
6. Insufficient funds error. Clik on Approve
7. Transaction Failed error. Failer to run txs. And even though the transaction failed i still get charged the fee.

**Expected behavior**
Money send to indicated address
**Screenshots**
Can't provide. The app doesn't let me do it.

**Smartphone (please complete the following information):**

- Device: Xiaomi MI 10 lite

- App Version [e.g. 3.3.0]

**Additional context**
It's outrages that I can't get my money out of this wallet I I'm loosing my money every day cause I can't invest it as I planned. Also I'm charged for each failed transation. There is no help available.  The wallet interface is tragic, it's not that hard to create a user friendly wallet btw. And lastly I'm so happy that now I have to basically work for free and raise a bug here for you to fix it. Normally I do this kind of things for a living testing apps. MAybe you should hire somebidy to do that and not expect the community to do it for free for you. But here I am doing it for free cause you basically rushed your not ready product to production. Hope to get my money back and never have to use this walllet again.

**Comment by waveform06** [comment]
txn = transaction
Click the lightning symbol in the app, click on the failed transaction (or try again and look at the latest)
click view on explorer and copy that link here

**Comment by domibe** [comment]
https://explorer.solana.com/tx/2V4EhuhedDDpzKo3bDpcrRU2198c9LJj9NP5dDwcJcG4FsQ3HyiYokdxk2T4XPynU5oP34zad9ad42YnT3XrzJFy?cluster=mainnet-beta

**Comment by ChewingGlass** [comment]
Try sending less sol. You still need sol left over to pay tx fees.
