### ISSUE TITLE
Wallet app SDK upgrade (DO BEFORE APRIL)

### ISSUE THREAD

**Issue by ChewingGlass** [helium/wallet-app#655]
ITMS-90725: SDK version issue - This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.

**Comment by ChewingGlass** [comment]
https://github.com/microsoft/appcenter/issues/2616

I think this is done.

**Comment by AjitKRuin** [comment]
@ChewingGlass , what have you done to update to sdk 17?

**Comment by ChewingGlass** [comment]
Just changed it in app center.

**Comment by AjitKRuin** [comment]
Could you please show me in screenshot
