### ISSUE TITLE
No rewards available for claim in app

### ISSUE THREAD

**Issue by Spewdog50** [helium/wallet-app#664]
Hi team, Energetic Indigo Weasel.
since last reward claim miner seems to be online and still producing IOT as per relay/HeliumGeek etc but I have 0 rewards to claim within app. 

This isn’t an issue with claiming but that the rewards being earned are not coming across to the app to be able to be claimed. 

hoping someone can help, any info needed please let me know.

Token address 9VcMWkmeup9oBMtbepRasNvhQZThGY7H7bXcFbdSCbxE

**Comment by Spewdog50** [comment]
I seem to have fixed this issue. 
This was on iOS, settings/general/iPhone storage. Locate app, offload app. Reinstall app, rewards are available for claim now

**Comment by abhay** [comment]
Very odd. Looks like there's some weird state that your app got into. Glad you were able to resolve.
