### ISSUE TITLE
Solana Transfer from Helium Wallet to Coinbase not received 

### ISSUE THREAD

**Issue by Greenmonster23** [helium/wallet-app#665]
On 2/9/24 I sent 4.73 Sol on hash 2sudnwtTQ9fNACFbe3t1T5v7mnbHWxXHW5e6XqcuT4qG88K6ZTtppfuZsgoGi85ihPqybGYjCCPAdbLMW5cvExxU
It is showing successful to my wallet address but never received the tokens.  Looking to see who can assist me in trying to figure this out.

thank you, 
Ramon

**Comment by ChewingGlass** [comment]
It sounds like you may be a victim of address poisoning. https://docs.helium.com/wallets/transaction-safety#address-poisoning

**Comment by ChewingGlass** [comment]
If you think you sent to the right address and have the tx hash to prove it, please contact the exchange.
