### ISSUE TITLE
Location assert for Wi-Fi APs

### ISSUE THREAD

**Issue by heatedlime** [helium/wallet-app#667]
Currently, within the black app, you can assert the location for outdoor Wi-Fi. 

You maybe able to do it for indoor; however, I'm not sure if it works. For outdoor Wi-Fi, height and azimuth requirements are required to be inputted; however, there is no section within the black wallet to input these variables before it prompts you to sign a transaction for the assert.

**Comment by ChewingGlass** [comment]
Closing this issue, as adding that seems to be part of a larger HIP.
