### ISSUE TITLE
decimal precision in hotspots list

### ISSUE THREAD

**Issue by qbaj** [helium/wallet-app#668]
**Describe the bug**
Too big decimal precision makes unreadable hotspot name.

**Screenshots**
![image](https://github.com/helium/wallet-app/assets/45151381/5fdf5cd2-e22b-4a30-842e-7d248be363bf)

**Smartphone (please complete the following information):**

- Device: iPhone13 mini 
- OS: iOS 17.3.1
- App Version v2.6.5

**Comment by ChewingGlass** [comment]
This will be fixed in 2.7.1
