### ISSUE TITLE
Unable to perform transactions in my Helium wallet using current black Helium Wallet app

### ISSUE THREAD

**Issue by medvyed** [helium/wallet-app#670]
I'm having a problem completing any transactions using my Helium wallet.  I can't **swap SOL to HNT** and I can't **send SOL to my Coinbase wallet**.  The transactions fail every time.  Is there something broken in my wallet?  Any [legitimate] help would be greatly appreciated.

**Swapping SOL to HNT...**
![IMG_5821](https://github.com/helium/wallet-app/assets/68880985/b117c9c5-15d8-4c19-acbd-7528de9f682c)
![IMG_5822](https://github.com/helium/wallet-app/assets/68880985/5e6ccbd8-898a-49a5-84fc-cecb9dba27ff)

**Sending SOL to Coinbase...**
![IMG_5818](https://github.com/helium/wallet-app/assets/68880985/d3c833b6-3c46-42d4-8b98-600ee4841cc1)
![IMG_5820](https://github.com/helium/wallet-app/assets/68880985/4144240a-4f20-4486-9e9e-8e5e68f8bd3b)

- Device: **iPhone 15 Pro Max**
- OS: **iOS 17.4 RC**
- App Version: **2.6.5 (1708462106)**

**Comment by medvyed** [comment]
Today I tested sending .5 HNT from Coinbase to my Helium wallet.  Worked fine and fast; no issues.

**Comment by waveform06** [comment]
Looks like this isn't an error but a cache issue showing an old balance.
