### ISSUE TITLE
Saved addresses in address book have changed after the Wallet App Update

### ISSUE THREAD

**Issue by hologr** [helium/wallet-app#672]
Dear Sir,

A very strange change happens in my black wallet's address book.

I saved in the address book of black wallet the address of Binance Solana wallet :
7yCJHsJof4KvvN9xoJoY7EBAGmbAPqEmUwiakgxenxvu

Transactions to Binance using the above saved address had already been done before.

After the latest update (v2.6.5), for some reason the above address in address book changes
without confirmation to a new address :
6wiDuEQjYm5VRAWXydHZzxCtARjGBHLYd4UEKQrGGMdL.
This is not my address and I didn't have any transaction with this address before.

I found this strange behavior when I sent SOL from my wallet using saved address and the
money went from my wallet 3UfzGBBDc8ZhLhroZD7ABQ5ckzkGVRZLfnHYxg3F68rM to the new unknown
saved wallet address 6wiDuEQjYm5VRAWXydHZzxCtARjGBHLYd4UEKQrGGMdL.
HASH of transaction:
57jrWpb2F6HjmsMybWV5DXQWJZB8tDAF5FK59GAqxawxFvfLTkvoq5Xc1STjc1BH61a8UJyU88afxYLursGd71C1

How does this change happens.?? 
The only transactions I am doing with my wallet is the IOT claim rewards and swapping them to solana with https://jup.ag.
Is this wallet address under your supervision and accidentally update my saved address.??
Ηow can i get my coins back.??
This looks like a nice Bug..!!
I would be grateful if you can do something about it.

Device: Xiaomi Redmi Note 7
OS: Android 10
App Version 2.6.5

**Comment by ChewingGlass** [comment]
It is not possible for the address in your address book to change. Not unless your phone itself is compromised.

**Comment by hologr** [comment]
It should be..
Please check the receiving address if it belongs to black wallet's company, developer team or test team.
It looks like this address changes with no reason.
Thanks

**Comment by ChewingGlass** [comment]
It doesn't belong to any helium entity, though it appears to have been an address on the old chain. Only thing I can think of is that you accidentally saved binance with the wallet address of a different contact of yours.

We have never had any other reports of addresses in address book changing on their own, so I don't think that's what happened.

**Comment by hologr** [comment]
It's a bit difficult to save this particular address because apart from sending to Binance, I don't do any other transactions nor do I have any other addresses saved. Also I'm very careful in any transaction with wallet. Looks a bit strange that the recipient's wallet has no transactions (except mine) and it looks frozen and inactive. Is there a way to inform the recipient about this wrong exchange..?? Thanks..
