### ISSUE TITLE
Transactions not sending 

### ISSUE THREAD

**Issue by heatedlime** [helium/wallet-app#679]
Transactions not sending out of the helium wallet 
![IMG_8392](https://github.com/helium/wallet-app/assets/104723888/ca5aaaee-e341-4ba5-8066-c4b62b09053a)

**Comment by heatedlime** [comment]
Was able to get one transaction to send, but now I can’t get others.

**Comment by ChewingGlass** [comment]
This is an issue with Solana congestion. We're improving the priority fee calculation in 2.7.1 but it's not a silver bullet. Scheduler changes are needed that are coming in Solana version 1.18. Until then, priority fee doesn't necessarily guarantee inclusion. Once a blockhash expires you will have to retry the transaction.
