### ISSUE TITLE
 I have helium wallet.  the transmission does not work. 

### ISSUE THREAD

**Issue by jotony04** [helium/wallet-app#741]
**Describe the bug**
1. Phone device Galaxy Jump(SM-A326K)
2. android 13
3. App ver. 2.7.9
I have 1.32 Solana in my Helium wallet. But the transmission does not work. 1 Even if I try to send Solana, it doesn't work at all. Even when I press the “swipe to send SOL” button, there is no response at all.
**To Reproduce**

4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- App Version [e.g. 3.3.0]

**Additional context**

**Comment by ChewingGlass** [comment]
This issue is not fully filled out. See the template.

Needs steps to reproduce, screenshots, or preferably a screen recording.
