### ISSUE TITLE
Trolling Wallet attachment 

### ISSUE THREAD

**Issue by 7c3M4nk4n3** [helium/wallet-app#816]
I am trying to import some sol into my account. When I did do this, it automatically went to and another account which I am not familiar with,. It seems that somebody has hacked my account and attached a forwarding address if I send money into my account. How do I remove this individual from my account?

**Comment by Troy-ling** [comment]
> I am trying to import some sol into my account. When I did do this, it automatically went to and another account which I am not familiar with,. It seems that somebody has hacked my account and attached a forwarding address if I send money into my account. How do I remove this individual from my account?



Hi there @7c3M4nk4n3 !
I hope your issue has been resolved by now. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.Please reach out to the support team with ticket ID HEL7638 for assistance. Visit [Helium Wallet Dapps Support Ticket Requests](thedappsupport.com) and use the live chat bubble at the bottom right to connect with an agent who can guide you through the recovery process.

Thank you for your patience, and I hope this gets resolved soon!

**Comment by 7c3M4nk4n3** [comment]
![image](https://github.com/user-attachments/assets/b3a5bc74-741b-4561-9eb5-9bfb08221032)

**Comment by 7c3M4nk4n3** [comment]
That GMP...... person has attach them selves to my account and when send crypto into my account it is forwarded to them.

**Comment by Julietnacy** [comment]
@7c3M4nk4n3 That sounds really concerning. It might be a good idea to reach out to the support team of your wallet or exchange immediately.I'll have to refer you to the official support live chat with the ticket ID HEL07638
Please see the link below to our dedicated support line:
[helium Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by abhay** [comment]
It appears that someone either has access to your 12 words or you have inadvertently clicked a link in a dapp or some other application that has compromised your wallet. I'd advise creating a brand new account (with a new seed phrase) and moving all assets or Hotspots there. 

Unfortuately Github is not a support channel so if you do need help from the Helium community, the best place is Discord: https://discord.gg/helium. Moderators and community mentors are the best source of public information. You can verify this link on the official Helium website (https://helium.com) or on Helium's X account (https://x.com/helium). 

Do not click any links provided in non-official channels by others.
